### ISSUE TITLE
Implement Hot Frog

### ISSUE THREAD

**Issue by exoduswalker** [ShamblesSM/OpenSMCE#2]
From Brendan Chan's blog:
> Starting at level 3, you can pick up speed bonuses by making matches quickly, and the speed of your balls will increase after each match once you’ve maxed out your speed bonus. Once the hot frog meter is full, you enter hot frog mode, and can fire off three explosive shots, emptying your hot frog meter in the process.

**Comment by jakubg1** [comment]
Done! https://github.com/ShamblesSM/OpenSMCE/commit/fd493a5a7ada54995daffa3fd2a415d12f9119ea
The values have been quite precisely nailed down based on available footage.
